export { default as PlusCircle } from "./PlusCircle.svg"
export { default as Logout } from "./Logout.svg"
export { default as Messages } from "./Messages.svg"
export { default as Settings } from "./Settings.svg"
export { default as Target } from "./Target.svg"